### ISSUE TITLE
No longer scraping

### ISSUE THREAD

**Issue by CloCkWeRX** [nik3daz/newcastle_development_applications#1]
https://www.planningalerts.org.au/authorities/newcastle

```
/app/vendor/bundle/ruby/2.0.0/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:308:in `fetch' : 404 => Net::HTTPNotFound for http://www.newcastle.nsw.gov.au/building_and_planning/da_assessment/current_das/current_das -- unhandled response (Mechanize::ResponseCodeError)
    from /app/vendor/bundle/ruby/2.0.0/gems/mechanize-2.7.3/lib/mechanize.rb:440:in `get'
    from scraper.rb:89:in `<main>'
```

**Comment by CloCkWeRX** [comment]
Interestingly, it looks like they've shoved this into into JRPP.

`Joint Regional Planning Panel were established by the NSW State Government on 1 July 2009. The Regional Panels will determine a range of developments, including all developments with a value of more than $20 million, that are not classified as being of State significance.`

**Comment by CloCkWeRX** [comment]
@Henare - with this kind of scenario, do we just want to disable it on the main planning alerts site since it's superceded? From the looks of it, the NSW JRPP scraper is happy and has examples for Fairfield, Parramatta, & Campbelltown currently being exhibited; so those scrapers could be put out to pasture as well.

**Comment by henare** [comment]
@CloCkWeRX I'm not sure it's superseded. As I understand it the JRPP only does a subset of DAs, the council still determines lots: http://www.newcastle.nsw.gov.au/Development/Development-Applications/Current-approved-DA-s

**Comment by henare** [comment]
I've also enabled issues on the PA fork of this in case we want to open issue there instead: https://github.com/planningalerts-scrapers/newcastle_development_applications/issues
